INFO:root:XWEAT started
Running Test true
Traceback (most recent call last):
  File "xweat/weat.py", line 745, in <module>
    args = main()
  File "xweat/weat.py", line 637, in main
    train_weat(args)
  File "xweat/weat.py", line 697, in train_weat
    raise ValueError("Only WEAT 1 to 10 and es1 and es2 are supported")
ValueError: Only WEAT 1 to 10 and es1 and es2 are supported
